        <!-- Page Header-->
        <header class="masthead" >
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1><?= esc($params['article']['title']); ?></h1>
                            <h2 class="subheading"><?= esc($params['article']['introduction']); ?> </h2>
                            <p class="meta">
                                Wrote by <?= esc($params['article']['creator']); ?>  <?= $params['article']['created_at']; ?>
                            </p>

                            <?php if($params['article']['created_at'] != $params['article']['modified_at'] ): ?>
                            <p class="meta">
                                Modified : <?= $params['article']['modified_at']; ?>
                            </p>
                            <?php endif; ?>

                        </div>
                        
                    </div>
                </div>
            </div>
        </header>

        <!-- Post Content-->
        <div class="container d-flex align-items-center justify-content-center">
            <img src="<?= 'public/assets/img/' . $params['article']['picture']; ?>" style="width:20%" class="img-fluid" alt="Picture of article">
        </div>
        
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <span id="articleview" style="overflow-wrap: break-word;">
                            <?= $params['article']['content']; ?>
                        </span>
                    </div>
                </div>
            </div>
        </article>
    


