<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <style>

        html, body {
            height: 100%;
        }

        body {
            background-color: lightgray;
            display: flex;
            align-items: center;
        }

        .form {
            width: 100%;
            margin: auto;
            max-width: 25rem;
        }

</style>

</head>
<body class="text-center">
    
    <main class="form">

        <?php if(isset($_SESSION['info'])): ?>   
            <div style="margin-top: 5rem;" class="alert alert-danger" role="alert">
                <?= $_SESSION['info']; ?>
            </div>
            <?php unset($_SESSION['info']);
        endif; ?>  

        <a href="/"><h1>My blog</h1></a>

        <h2>Register</h2>

        <form method="POST" action="/registerServer" style="margin-bottom: 1rem;">

            <div class="form-floating" style="margin-bottom: 1rem;" >
                <input type="text" name="username" class="form-control" minlength="3" required id="username" placeholder="Username">
                <label for="username">Username</label>
            </div>

            <div class="form-floating" style="margin-bottom: 1rem;">
                <input type="password" name="password" class="form-control" minlength="3" required id="password" placeholder="Password">
                <label for="password">Password</label>
            </div>

            <div class="form-floating" style="margin-bottom: 1rem;">
                <input type="password" name="password_confirm" class="form-control" minlength="3" required id="password_confirm" placeholder="Password again">
                <label for="password_confirm">Password again</label>
            </div>

            <button style="width: 100%;" class="btn btn-lg btn-primary" type="submit">Register</button>
        </form>

        <p>You can reach login here : <a href="/login">Login</a></p>
        <p>Go back to <a href="/">Home</a></p>

    </main>

  </body>
</html>
